services:
  frontend:
    build:
      context: frontend
      target: development
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /code/node_modules
    networks:
      - public
    depends_on:
      - backend
  backend:
    build:
      args:
      - NODE_ENV=development
      context: backend
      target: development
    command: sh -c "npm run dev"
    environment:
      - DEV_DATABASE_URL=${MONGO_URI}
      - NODE_ENV=development
    ports:
      - 8000:8000
      - 9229:9229
      - 9230:9230
    volumes:
      - ./backend/src:/code/src:ro
      - ./backend/package.json:/code/package.json
      - ./backend/package-lock.json:/code/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - public
      - private
networks:
  public:
  private:
volumes:
  back-notused:
